# To build: hugo -D -d docs --cleanDestinationDir --gc
# To server: hugo server -D -w
# To create new post: hugo new --kind post category-folder/subfolder

baseURL = "https://bykoga.com/"
languageCode = "en-us"
title = "byKoga"
theme = "themebykoga"
Paginate = 20
disableKinds = ["taxonomyTerm", "taxonomy"]

[imaging]
    resampleFilter = "box"
    quality = 75
    anchor = "smart"
    bgColor = "#ffffff"

[imaging.exif]
    includeFields = ""
    excludeFields = ""
    disableDate = false
    disableLatLong = false

[params]
     Description = "A blog, portfolio, and personal website! [byKoga]"