# Remember the line to build: hugo -D -d docs --cleanDestinationDir

baseURL = "https://gitbykoga.github.io/"
languageCode = "en-us"
title = "byKoga"
theme = "themebykoga"

disableKinds = ["taxonomyTerm", "taxonomy"]