# To build: hugo -D -d docs --cleanDestinationDir --gc
# To server: hugo server -D -w
# To create new category: hugo new --kind category <category name>
# To create new post: hugo new --kind post <category name>/<post name>
# To create new tag: hugo new tags/<tag name>/_index.md

baseURL = "https://bykoga.com/"
languageCode = "en-us"
title = "byKoga"
theme = "themebykoga"

[markup.goldmark.renderer]
    unsafe = true

# Remove tags and categories, I'll create the tags page manually
# disableKinds = ["taxonomy", "term"]
# ignoreErrors = ["error-disable-taxonomy"] # you will get a console error message without this
[permalinks]
    tag = "tags"
    category = "/:slug/"

Paginate = 20

[imaging]
    resampleFilter = "box"
    quality = 75
    anchor = "smart"
    bgColor = "#ffffff"

[imaging.exif]
    includeFields = ""
    excludeFields = ""
    disableDate = false
    disableLatLong = false

[params]
     Description = "A blog, portfolio, and personal website! [byKoga]"
